[workspace]
channels = ["conda-forge"]
name = "atc"
platforms = ["linux-64", "win-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
click = ">=8.1.8,<9"
pony = ">=0.7.18,<0.8"
pyyaml = ">=6.0.2,<7"

[tool.pixi.scripts]
atc = "python -m atc"
