[workspace] 
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[dependencies] 
atc = { path = "." }
click = ">=8.1.8,<9"
pyyaml = ">=6.0.2,<7"
pony = ">=0.7.18,<0.8"
tabulate = ">=0.9.0,<0.10"
rich = ">=14.0.0,<15"

[tasks] 
start = "atc"

[package] 
name = "atc"
version = "0.1.0"

[package.build] 
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies] 
hatchling = "==1.26.3"
