[project]
dependencies = ["clicK", "pyyaml", "pony", "rich"]                              
name = "atc"
requires-python = ">= 3.11"
scripts = { atc = "atc:cli" } 
version = "0.1.0"

[build-system] 
build-backend = "hatchling.build"
requires = ["hatchling"]